Pretty up dashboard
JonR205/KTSOCM pull request #6
Opened 2023-08-20 15:00 UTC by JonR205

2023-08-20 15:01 UTC, JonR205 commented
@LewisRhine I don't know how to "assign" you to this

2023-08-21 00:00 UTC, LewisRhine requested changes

2023-08-21 00:00 UTC, LewisRhine commented on src/context/sessionContext.ts
> +export const SessionContext = createContext<Session | null>(null)
Change to lower case first letter "sessionContext".

2023-08-21 14:32 UTC, LewisRhine commented on src/componants/DataslateCard.tsx
> +        <div className="content">Current Spec Ops: None</div>
this also needs to be "card-content" instead of "content"

2023-08-22 15:03 UTC, LewisRhine approved these changes

2023-08-22 19:03 UTC, merged